volumes:
  api-db:
    driver: local

networks:
  api-network:

services:
  postgres-db:
    image: "postgres:17.4-alpine"
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: [ "5432:5432" ]
    volumes:
      - api-db:/var/lib/postgresql/data
    networks:
      - api-network
  security-api:
    build: .
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports: [ "8081:8080" ]
    networks:
      - api-network