spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default-schema: public
        format-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

auth:
  jwt:
    secret-key: ebf96689f4d8e85fc5e6e2fd9f59d70775691d57ee0f2e81f35d10181387f963
    expiration-time: 1800 # in seconds
  refresh-token:
    expiration-time: 86400 # in seconds
    cleanup-interval: 3600000
  permission:
    permit-all:
      - /api/auth/**
  cors:
    allowed-headers:
      - Authorization
      - Content-Type
    allowed-methods:
      - GET
      - POST
    allowed-origins:
      - http://localhost:8080
